version: "3.3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: aaronch
      POSTGRES_PASSWORD: aaronch26
    ports:
      - 5432:5432
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=aaronch.dev@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80